/tracking/verbose 0
/event/verbose 0

/tracking/storeTrajectory 1
/tracking/discardParticleTrajectory opticalphoton

/rat/db/set DETECTOR experiment "ANNIE" 
/rat/db/set DETECTOR geo_file "ANNIE/ANNIE_run2_config13_scan.geo" 
/run/initialize
/rat/proc splitevdaq
/rat/proclast outanniecluster
/rat/procset file "ANNIE_ambe_neutron_test_michelChargeTunedQE_0.8xR.cluster.ntuple.root" 
/generator/add combo spectrum:point
/generator/vtx/set neutron ambe_test
/generator/pos/set 0.0 -33.8 1749.4


/run/beamOn 1000
