#/glg4debug/glg4param omit_muon_processes  1.0
#/glg4debug/glg4param omit_hadronic_processes  1.0


/tracking/verbose 0
/tracking/storeTrajectory 1
/tracking/discardParticleTrajectory opticalphoton

/rat/proc prune
/rat/procset prune "mc.track:opticalphoton"

/rat/db/set DETECTOR experiment "ANNIE"
/rat/db/set DETECTOR geo_file "ANNIE/ANNIE_run2_config13_scan.geo"

/run/initialize

/rat/proc simpledaq
/rat/proc count
/rat/procset update 10
/rat/proc fitcentroid

/rat/proclast outroot

/generator/add combo gun:point
#/generator/vtx/set mu- 0 0 1 1000.0
#/generator/vtx/set gamma 0 0 1 2.0
/generator/pos/set 0.0 -133.3 1724

/vis/open VRML2FILE
#/vis/open DAWNFILE
/vis/verbose errors
/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi 90. 0.
/vis/viewer/set/style wireframe
/vis/scene/add/axes 0 0 0 1 m
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
/vis/scene/add/hits
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#/vis/filtering/trajectories/particleFilter-0/invert true
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e- blue
#/vis/scene/endOfEventAction accumulate
/vis/scene/endOfRunAction refresh
/vis/verbose warnings
/vis/viewer/flush

/run/beamOn 1

/vis/viewer/flush
