/tracking/verbose 0
/event/verbose 0

/tracking/storeTrajectory 0
/tracking/discardParticleTrajectory opticalphoton

/process/had/particle_hp/use_photo_evaporation true
/process/had/particle_hp/do_not_adjust_final_state true

/rat/db/set DETECTOR experiment "ANNIE" 
/rat/db/set DETECTOR geo_file "ANNIE/ANNIE_run2_config14_scan.geo"
/rat/db/load ANNIE/ANNIE_AmBesource.geo
/rat/nCapPhysics/setnCaptureModel ANNRI

/run/initialize
#/rat/physics/scintillation/meanPhotonsPerSecondary 1
/rat/proc splitevdaq
/rat/proclast outanniecluster
#/rat/proclast outntuple
#/rat/procset file "ANNIE_AmBePointTest_P3_yM102_wTyvek100_wPVC100_bPE000_bPVC000.ntuple.root" 
/rat/procset file "ANNIE_AmBeSourceTest.ntuple.root" 

#/generator/add combo spectrum:point
#/generator/vtx/set neutron ambe_neutron_spectrum
#/generator/pos/set 100.0 200.0 300.0

/generator/add combo spectrum:regexfill
/generator/vtx/set neutron ambe_neutron_spectrum
/generator/pos/set ^AmBeSource*

/run/beamOn 100
