/glg4debug/glg4param omit_muon_processes  0.0
/glg4debug/glg4param omit_hadronic_processes  1.0

/tracking/verbose 0
/event/verbose 0

/tracking/storeTrajectory 0
/tracking/discardParticleTrajectory opticalphoton

/rat/db/set DETECTOR experiment "ANNIE"
/rat/db/set DETECTOR geo_file "ANNIE/ANNIE_run2_config13_scan_sandi.geo" 

/run/initialize

/rat/proc splitevdaq
/rat/proc count
/rat/procset update 10

/rat/proclast outanniecluster
/rat/procset file "SANDI_water_Rh106_BetaSpectrum.ntuple.root"

/generator/add combo spectrum:point
/generator/vtx/set e- Rh106_BetaSpectrum
/generator/pos/set 0.0 0.0 1749.4

#/generator/pos/set ^detector*|^ncv*

#/generator/add combo spectrum:point
#/generator/vtx/set e- michel
#/generator/pos/set 0.0 -33.8 1749.4

/run/beamOn 30
