/process/eLoss/StepFunction 0.002 0.001 mm
#/run/setCutForAGivenParticle e- 1.0 mm

/rat/physics/enableCerenkov false
/rat/physics/setCerenkovMaxNumPhotonsPerStep 1000000000


/glg4debug/glg4param omit_muon_processes  0.0
/glg4debug/glg4param omit_hadronic_processes  1.0

/tracking/verbose 0
/event/verbose 0

/tracking/storeTrajectory 0
/tracking/discardParticleTrajectory opticalphoton


/rat/proc prune
/rat/procset prune "mc.track:opticalphoton"
/rat/procset prune "mc.track:e-"
/rat/procset prune "mc.track:neutron"

/rat/db/set DETECTOR experiment "ANNIE"
/rat/db/set DETECTOR geo_file "ANNIE/ANNIE_run2_config13_scan.geo"
/rat/db/load ANNIE/SANDI1_WbLS_Vessel.geo

/run/initialize

/rat/proc simpledaq
/rat/proc count
/rat/procset update 10
/rat/proc fitcentroid

#/rat/proclast outroot
#/rat/procset file "sandi_electron_1MeV.root"

/rat/proclast outntuple
/rat/procset file "sandi_elec_1MeV_RoverRange0.002_finalRange1.0um_noCer_largeNumCer.ntuple.root"

#/generator/add combo gun:point
#/generator/vtx/set mu- 0 0 1 1000.0
#/generator/pos/set 0.0 -133.3 1724

#/generator/add combo gun:regexfill
#/generator/pos/set ^detector*|^ncv*
#/generator/vtx/set neutron 0 0 0 5

/generator/add combo gun:regexfill
/generator/pos/set ^wblsvolume_liquid*|^ncv*
/generator/vtx/set e- 0.0 0.0 0.0 1.0

/run/beamOn 2000
