/glg4debug/glg4param omit_muon_processes  0.0
/glg4debug/glg4param omit_hadronic_processes  1.0

/tracking/verbose 0
/event/verbose 0

/tracking/storeTrajectory 0
/tracking/discardParticleTrajectory opticalphoton

/rat/proc prune
/rat/procset prune "mc.track:opticalphoton"
/rat/procset prune "mc.track:e-"
/rat/procset prune "mc.track:neutron"

/rat/db/set DETECTOR experiment "ANNIE"
/rat/db/set DETECTOR geo_file "ANNIE/ANNIE_run2_config13_scan.geo"
#/rat/db/load ANNIE/ANNIE_WbLS_Volume_Johann.geo

/run/initialize

/rat/proc simpledaq
/rat/proc count
/rat/procset update 10
/rat/proc fitcentroid

#/rat/proclast outroot
#/rat/procset file "sandi_electron_1MeV.root"

/rat/proclast outntuple
/rat/procset file "ANNIE_throughgoing_muon_test.ntuple.root"

# RATPAC center position relative to tank pmts: (0.0, -33.8, 1749.4)
# Another possibility is (0.0 -133.3 1724)

/generator/add combo gun:point
/generator/vtx/set mu- 0 -1 0 1000.0
/generator/pos/set 0.0 -133.3 1724
/run/beamOn 1

/generator/vtx/set mu- 0 -1 0 1000.0
/generator/pos/set 0.0 -133.3 1724
/run/beamOn 1

/generator/vtx/set mu- 0 -1 0 1000.0
/generator/pos/set 0.0 -133.3 1724
/run/beamOn 1

/generator/vtx/set mu- 0 -1 0 1000.0
/generator/pos/set 0.0 -133.3 1724
/run/beamOn 1
