/glg4debug/glg4param omit_muon_processes  0.0
/glg4debug/glg4param omit_hadronic_processes  1.0

/tracking/verbose 0
/event/verbose 0

/tracking/storeTrajectory 0
/tracking/discardParticleTrajectory opticalphoton


/rat/proc prune
/rat/procset prune "mc.track:opticalphoton"
/rat/procset prune "mc.track:e-"
/rat/procset prune "mc.track:neutron"

/rat/db/set DETECTOR experiment "ANNIE"
/rat/db/set DETECTOR geo_file "ANNIE/ANNIE_run2_config13_scan.geo"
/rat/db/load ANNIE/SANDI1_WbLS_Vessel.geo

/run/initialize

/rat/proc splitevdaq
/rat/proc count
/rat/procset update 10


#/rat/proclast outroot
#/rat/procset file "ANNIE_michel_electron_test.root"

/rat/proclast outanniecluster
/rat/procset file "SANDI_LY095_REEMChinaPaper_noQETuning_center_TILTED.ntuple.root"

#/generator/add combo spectrum:regexfill
#/generator/vtx/set e- michel
#/generator/pos/set ^detector*|^ncv*

/generator/add combo spectrum:point
/generator/vtx/set e- michel
/generator/pos/set 0.0 -33.8 1749.4

/run/beamOn 1000
