/glg4debug/glg4param omit_muon_processes  0.0
/glg4debug/glg4param omit_hadronic_processes  1.0

/tracking/verbose 0
/event/verbose 0

/tracking/storeTrajectory 1
/tracking/discardParticleTrajectory opticalphoton

/rat/proc prune
/rat/procset prune "mc.track:opticalphoton"
/rat/procset prune "mc.track:e-"
/rat/procset prune "mc.track:neutron"

/rat/db/set DETECTOR experiment "ANNIE"
/rat/db/set DETECTOR geo_file "ANNIE/ANNIE_run2_config13_scan.geo"
#/rat/db/load ANNIE/SANDI1_WbLS_Vessel.geo

/run/initialize

/rat/proc splitevdaq
/rat/proc count
/rat/procset update 10
/rat/proc fitcentroid

#/rat/proclast outroot
#/rat/procset file "sandi_electron_1MeV.root"

/rat/proclast outanniecluster
/rat/procset file "ANNIE_throughgoing_muon_test_2.ntuple.root"

# RATPAC center position relative to tank pmts: (0.0, -33.8, 1749.4)

/generator/add combo gun:point
#/generator/vtx/set mu- 0 -1 0 2000.0
#/generator/pos/set 0.0 -33.8 1749.4
#/run/beamOn 1

/generator/vtx/set mu- -0.01690 -0.03806 0.99913 5047.5
/generator/pos/set -462.36 -1328.99 63.00
/run/beamOn 2

   
