/glg4debug/glg4param omit_muon_processes  0.0
/glg4debug/glg4param omit_hadronic_processes  1.0

/tracking/verbose 0
/event/verbose 0

/tracking/storeTrajectory 1
/tracking/discardParticleTrajectory opticalphoton


/rat/proc prune
/rat/procset prune "mc.track:opticalphoton"

/rat/db/set DETECTOR experiment "ANNIE"
/rat/db/set DETECTOR geo_file "ANNIE/ANNIE_run2_config13_scan.geo"
/rat/db/load ANNIE/ANNIE_WbLS_Volume_Johann.geo

#/PMTOpticalModel/verbose 3

#/process/eLoss/StepFunction 0.01 0.01 mm
/run/initialize

/rat/proc splitevdaq

/rat/proclast outanniecluster
/rat/procset file "SANDI_neutron_splitevdaq_test.ntuple.root"

/generator/add combo gun:regexfill
/generator/vtx/set neutron 0 0 0 0.000001
#/generator/pos/set ^detector*|^wblsvolume_liquid*
/generator/pos/set ^pmt_enclosed*|^wblsvolume_liquid*

#/generator/add combo gun:point
#/generator/vtx/set neutron 0 0 0 0.000001
#/generator/pos/set 0.0 -33.8 1749.4

/run/beamOn 100
