#/glg4debug/glg4param omit_muon_processes  0.0
#/glg4debug/glg4param omit_hadronic_processes  1.0

/tracking/verbose 0
/event/verbose 0

#/tracking/storeTrajectory 1
#/tracking/discardParticleTrajectory opticalphoton


#/rat/proc prune
#/rat/procset prune "mc.track:opticalphoton"

/rat/db/set DETECTOR experiment "ANNIE"
/rat/db/set DETECTOR geo_file "ANNIE/ANNIE_run2_config13_scan.geo"
/rat/db/load ANNIE/ANNIE_WbLS_Volume_Johann.geo

#/PMTOpticalModel/verbose 3

#/process/eLoss/StepFunction 0.01 0.01 mm
/run/initialize

/rat/proc simpledaq

/rat/proclast outanniecluster
#/rat/proclast outntuple
/rat/procset file "SANDI_muon_neutron_outanniecluster_test.ntuple.root"

#/generator/add combo gun:regexfill
#/generator/vtx/set neutron 0 0 0 100.0
#/generator/pos/set ^detector*|^wblsvolume_liquid*
#/generator/pos/set ^pmt_enclosed*|^wblsvolume_liquid*
#/generator/pos/set ^wblsvolume_liquid*


/generator/add external external:poisson:"../../macros/test.dat"

/run/beamOn 50
